
package ifpb.ads.pos.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculadoraSOAPService", targetNamespace = "http://soap.pos.ads.ifpb/", wsdlLocation = "http://localhost:8080/CalculadoraSOAPService/CalculadoraSOAP?wsdl")
public class CalculadoraSOAPService
    extends Service
{

    private final static URL CALCULADORASOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULADORASOAPSERVICE_EXCEPTION;
    private final static QName CALCULADORASOAPSERVICE_QNAME = new QName("http://soap.pos.ads.ifpb/", "CalculadoraSOAPService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/CalculadoraSOAPService/CalculadoraSOAP?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULADORASOAPSERVICE_WSDL_LOCATION = url;
        CALCULADORASOAPSERVICE_EXCEPTION = e;
    }

    public CalculadoraSOAPService() {
        super(__getWsdlLocation(), CALCULADORASOAPSERVICE_QNAME);
    }

    public CalculadoraSOAPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULADORASOAPSERVICE_QNAME, features);
    }

    public CalculadoraSOAPService(URL wsdlLocation) {
        super(wsdlLocation, CALCULADORASOAPSERVICE_QNAME);
    }

    public CalculadoraSOAPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULADORASOAPSERVICE_QNAME, features);
    }

    public CalculadoraSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculadoraSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculadoraSOAP
     */
    @WebEndpoint(name = "CalculadoraSOAPPort")
    public CalculadoraSOAP getCalculadoraSOAPPort() {
        return super.getPort(new QName("http://soap.pos.ads.ifpb/", "CalculadoraSOAPPort"), CalculadoraSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculadoraSOAP
     */
    @WebEndpoint(name = "CalculadoraSOAPPort")
    public CalculadoraSOAP getCalculadoraSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.pos.ads.ifpb/", "CalculadoraSOAPPort"), CalculadoraSOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULADORASOAPSERVICE_EXCEPTION!= null) {
            throw CALCULADORASOAPSERVICE_EXCEPTION;
        }
        return CALCULADORASOAPSERVICE_WSDL_LOCATION;
    }

}
