
package ifpb.ads.pos.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculadoraSOAP", targetNamespace = "http://soap.pos.ads.ifpb/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculadoraSOAP {


    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "somarSOAP", targetNamespace = "http://soap.pos.ads.ifpb/", className = "ifpb.ads.pos.soap.SomarSOAP")
    @ResponseWrapper(localName = "somarSOAPResponse", targetNamespace = "http://soap.pos.ads.ifpb/", className = "ifpb.ads.pos.soap.SomarSOAPResponse")
    @Action(input = "http://soap.pos.ads.ifpb/CalculadoraSOAP/somarSOAPRequest", output = "http://soap.pos.ads.ifpb/CalculadoraSOAP/somarSOAPResponse")
    public int somarSOAP(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtrair", targetNamespace = "http://soap.pos.ads.ifpb/", className = "ifpb.ads.pos.soap.Subtrair")
    @ResponseWrapper(localName = "subtrairResponse", targetNamespace = "http://soap.pos.ads.ifpb/", className = "ifpb.ads.pos.soap.SubtrairResponse")
    @Action(input = "http://soap.pos.ads.ifpb/CalculadoraSOAP/subtrairRequest", output = "http://soap.pos.ads.ifpb/CalculadoraSOAP/subtrairResponse")
    public int subtrair(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

}
