
package br.edu.ifpb.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NewsSOAPService", targetNamespace = "http://service.ifpb.edu.br/", wsdlLocation = "http://localhost:8080/pos-news/NewsSOAPService?wsdl")
public class NewsSOAPService
    extends Service
{

    private final static URL NEWSSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException NEWSSOAPSERVICE_EXCEPTION;
    private final static QName NEWSSOAPSERVICE_QNAME = new QName("http://service.ifpb.edu.br/", "NewsSOAPService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/pos-news/NewsSOAPService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NEWSSOAPSERVICE_WSDL_LOCATION = url;
        NEWSSOAPSERVICE_EXCEPTION = e;
    }

    public NewsSOAPService() {
        super(__getWsdlLocation(), NEWSSOAPSERVICE_QNAME);
    }

    public NewsSOAPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NEWSSOAPSERVICE_QNAME, features);
    }

    public NewsSOAPService(URL wsdlLocation) {
        super(wsdlLocation, NEWSSOAPSERVICE_QNAME);
    }

    public NewsSOAPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NEWSSOAPSERVICE_QNAME, features);
    }

    public NewsSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NewsSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NewsSOAP
     */
    @WebEndpoint(name = "NewsSOAPPort")
    public NewsSOAP getNewsSOAPPort() {
        return super.getPort(new QName("http://service.ifpb.edu.br/", "NewsSOAPPort"), NewsSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NewsSOAP
     */
    @WebEndpoint(name = "NewsSOAPPort")
    public NewsSOAP getNewsSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ifpb.edu.br/", "NewsSOAPPort"), NewsSOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NEWSSOAPSERVICE_EXCEPTION!= null) {
            throw NEWSSOAPSERVICE_EXCEPTION;
        }
        return NEWSSOAPSERVICE_WSDL_LOCATION;
    }

}
